public class Calculator {
    public static void add(integer val1,integer val2){
        System.debug(val1+val2);
    }
    public static void substract(integer val1,integer val2){
        System.debug(val1-val2);
    }
    public static void multiply(integer val1,integer val2){
        System.debug(val1*val2);
    }
    public static void divide(integer val1,integer val2){
        System.debug(val1/val2);
    }
}